@startuml
entity "Продавец" {
    +идентификатор: INT <<PK>>
    +имя: VARCHAR
    +контактная_информация: VARCHAR
}

entity "Товар" {
    +идентификатор: INT <<PK>>
    +название: VARCHAR
    +описание: TEXT
    +количество: INT
    +цена: DECIMAL
    +идентификатор_продавца: INT <<FK>>
}

entity "Карточка_товара" {
    +идентификатор: INT <<PK>>
    +идентификатор_товара: INT <<FK>>
    +описание_карточки: TEXT
    +изображение: VARCHAR 
    +дата_создания: DATETIME
}

entity "Отзыв" {
    +идентификатор: INT <<PK>>
    +идентификатор_товара: INT <<FK>>
    +клиент: VARCHAR
    +оценка: INT
    +текст: TEXT
    +дата: DATETIME
}

entity "Сообщение" {
    +идентификатор: INT <<PK>>
    +идентификатор_товара: INT <<FK>>
    +клиент: VARCHAR
    +текст: TEXT
    +дата: DATETIME
}

entity "Заказ" {
    +идентификатор: INT <<PK>>
    +идентификатор_товара: INT <<FK>>
    +клиент: VARCHAR
    +дата_заказа: DATETIME
    +статус: VARCHAR
}

Продавец ||--o{ Товар
Товар ||--o{ Карточка_товара
Товар ||--o{ Отзыв
Товар ||--o{ Сообщение
Товар ||--o{ Заказ
@enduml
