@startuml
participant Продавец
participant Веб_Интерфейс
participant API_Сервер
participant БазаДанных
participant Email_Сервис

Продавец -> Веб_Интерфейс: Вводит данные нового товара
Веб_Интерфейс -> API_Сервер: Отправляет данные о новом товаре
API_Сервер -> БазаДанных: Сохраняет информацию о товаре
БазаДанных --> API_Сервер: Подтверждение сохранения


Продавец -> Веб_Интерфейс: Обновляет количество запасов
Веб_Интерфейс -> API_Сервер: Передает обновленные данные
API_Сервер -> БазаДанных: Обновляет запасы товара
БазаДанных --> API_Сервер: Подтверждение обновления

API_Сервер -> Email_Сервис: Отправка уведомления о успешном добавлении/обновлении товара
Email_Сервис --> API_Сервер: Подтверждение отправки письма


@enduml
